export default [{
    id: 'computed41/public-collision', improvement: 'R41-01', scenario: 'computed41/identity',
    gates: [{metric: 'initial', equals: 3}, {metric: 'final', equals: 4},
        {metric: 'deliveries', equals: 1}, {metric: 'strictConsumer', equals: true},
        {metric: 'strictDomainConsumer', equals: true},
        {metric: 'done', equals: true}],
}, {
    id: 'computed41/observer-lifetime', improvement: 'R41-02', scenario: 'computed41/lifetime',
    gates: [{metric: 'scalar', equals: 0}, {metric: 'collected', equals: true},
        {metric: 'controlAlive', equals: true}, {metric: 'ownersAlive', equals: true},
        {metric: 'failedBody', equals: true}, {metric: 'sourceScalar', equals: 0},
        {metric: 'sourceCollected', equals: true},
        {metric: 'viewCollected', equals: true}, {metric: 'sourceControlAlive', equals: true},
        {metric: 'evaluatedScalar', equals: 0}, {metric: 'obsoleteCollected', equals: true},
        {metric: 'switchValues', equals: true}, {metric: 'oldViewsPrecise', equals: true},
        {metric: 'retiredRightRuns', equals: '0,0'}, {metric: 'replacementRightRuns', equals: '0,0'},
        {metric: 'observedLeftRuns', equals: '1,1'}, {metric: 'observedLeftDeliveries', equals: '1,1'},
        {metric: 'observedLeftValues', equals: '41,41'},
        {metric: 'switchedSourcesCollected', equals: true}, {metric: 'retainedViewsAlive', equals: true},
        {metric: 'switchingOwnersAlive', equals: true},
        {metric: 'final', equals: 1}, {metric: 'deliveries', equals: 1}, {metric: 'done', equals: true}],
}, ...[500, 1000, 2000].map(D => ({
    id: `computed41/dependencies-${D}`, improvement: 'R41-03',
    scenario: 'computed41/dependencies', args: [String(D)],
    gates: [{metric: 'initial', equals: D},
        {metric: 'values', equals: [2 * D, D, 2 * D, D, 2 * D, D, 2 * D].join(',')},
        {metric: 'deliveries', equals: 7}, {metric: 'comparisons', equals: 0},
        {metric: 'edgeWork', equals: 8 * (D + 1)}, {metric: 'work', max: 8 * (D + 1)},
        {metric: 'retainedAttaches', equals: 0}, {metric: 'retainedReleases', equals: 0},
        {metric: 'done', equals: true}],
}))];
