export default [
    {
        id: 'resource41/memo-data@1000', improvement: 'R41-04',
        scenario: 'resource41/memo-data', args: [],
        gates: [
            {metric: 'hookUnrelated', equals: 1},
            {metric: 'hookStable', equals: 1},
            {metric: 'hookRefresh', equals: 3},
            {metric: 'hookText', equals: 'Grace'},
        ],
    },
    {
        id: 'resource41/machinery@1000', improvement: 'R41-04',
        scenario: 'resource41/memo-data', args: [],
        gates: [
            {metric: 'accessorDefinitions', equals: 0},
            {metric: 'readTreeWeakMaps', equals: 0},
            {metric: 'stableSelectorCalls', equals: 0},
            {metric: 'stableSubscriptionAdds', equals: 0},
            {metric: 'stableSubscriptionRemoves', equals: 0},
            {metric: 'stableChecksum', equals: 1000},
            {metric: 'subscriptionsBalanced', equals: true},
            {metric: 'ownersAfterUnmount', equals: 0},
            {metric: 'reevaluationSelectorCalls', equals: 1},
            {metric: 'directFlatObjectReevaluationSets', equals: 32},
            {metric: 'directFlatArrayReevaluationSets', equals: 32},
            {metric: 'directFlatObjectReevaluationSetCopies', equals: 0},
            {metric: 'directFlatArrayReevaluationSetCopies', equals: 0},
            {metric: 'directFlatAllocationControl', equals: true},
            {metric: 'graphAllocationControl', equals: true},
            {metric: 'allocationCaptureControl', equals: true},
        ],
    },
    {
        id: 'resource41/dependency-precision', improvement: 'control',
        scenario: 'resource41/memo-data', args: [],
        gates: [
            {metric: 'hookUnreadParents', equals: 0},
            {metric: 'hookUnreadChildren', equals: 0},
            {metric: 'leafParentDeliveries', equals: 1},
            {metric: 'leafChildDeliveries', equals: 1},
            {metric: 'leafText', equals: 'Leaf'},
        ],
    },
    {
        id: 'resource41/snapshot-lifecycle', improvement: 'control',
        scenario: 'resource41/memo-data', args: [],
        gates: [
            {metric: 'capturedText', equals: 'Ada'},
            {metric: 'loadsInRender', equals: 0},
            {metric: 'localOverrideText', equals: 'local'},
            {metric: 'localOverrideCacheText', equals: 'Grace'},
            {metric: 'done', equals: true},
        ],
    },
    {
        id: 'resource41/class-positive-control@1000', improvement: 'control',
        scenario: 'resource41/memo-data', args: [],
        gates: [
            {metric: 'classUnrelated', equals: 1},
            {metric: 'classStable', equals: 1},
            {metric: 'classRefresh', equals: 2},
            {metric: 'classText', equals: 'Grace'},
            {metric: 'selectionUnreadParents', equals: 0},
            {metric: 'selectionUnreadChildren', equals: 0},
            {metric: 'selectionLeafParentDeliveries', equals: 1},
            {metric: 'selectionLeafChildDeliveries', equals: 1},
            {metric: 'selectionLeafText', equals: 'Leaf'},
            {metric: 'selectionText', equals: 'Grace'},
        ],
    },
    {
        id: 'resource41/inline-cost@1000', improvement: 'control',
        scenario: 'resource41/memo-data', args: [],
        gates: [
            {metric: 'inlineSelectorCalls', equals: 1000},
            {metric: 'inlineChecksum', equals: 1000},
            {metric: 'inlineStable', equals: 1},
            {metric: 'inlineAccessors', equals: 0},
        ],
    },
];
