export default [
    {
        id: 'resource40/hook-renders@50', improvement: 'R40-04',
        scenario: 'resource40/hook-renders', args: [],
        gates: [
            {metric: 'hookAvailable', equals: true},
            {metric: 'hookMountRenders', equals: 2},
            {metric: 'hookEqualRefreshRenders', equals: 2},
            {metric: 'hookRefetches', equals: 50},
            {metric: 'hookTextUnchanged', equals: true},
            {metric: 'hookTextCorrect', equals: true},
            {metric: 'classMountRenders', equals: 2},
            {metric: 'classEqualRefreshRenders', equals: 2},
            {metric: 'classRefetches', equals: 50},
            {metric: 'classTextUnchanged', equals: true},
            {metric: 'classTextCorrect', equals: true},
            {metric: 'done', equals: true},
        ],
    },
    {
        id: 'resource40/field-precision', improvement: 'R40-04',
        scenario: 'resource40/field-precision', args: [],
        gates: [
            {metric: 'hookAvailable', equals: true},
            {metric: 'hookNameUnreadRenders', equals: 0},
            {metric: 'hookNameReadRenders', equals: 1},
            {metric: 'hookErrorUnreadRenders', equals: 0},
            {metric: 'hookErrorReadRenders', equals: 1},
            {metric: 'hookOtherUnreadRenders', equals: 0},
            {metric: 'hookOtherReadRenders', equals: 1},
            {metric: 'hookTextCorrect', equals: true},
            {metric: 'classNameUnreadRenders', equals: 0},
            {metric: 'classNameReadRenders', equals: 1},
            {metric: 'classErrorUnreadRenders', equals: 0},
            {metric: 'classErrorReadRenders', equals: 1},
            {metric: 'classOtherUnreadRenders', equals: 1},
            {metric: 'classOtherReadRenders', equals: 1},
            {metric: 'classTextCorrect', equals: true},
            {metric: 'done', equals: true},
        ],
    },
    {
        id: 'resource40/no-load-in-render', improvement: 'R40-04',
        scenario: 'resource40/no-load-in-render', args: [],
        gates: [
            {metric: 'hookAvailable', equals: true},
            {metric: 'hookLoaderCallsInRender', equals: 0},
            {metric: 'hookLoaderCallsBeforeCommit', equals: 0},
            {metric: 'hookLoaderCallsAfterCommit', equals: 1},
            {metric: 'hookTextCorrect', equals: true},
            {metric: 'classLoaderCallsInRender', equals: 0},
            {metric: 'classLoaderCallsBeforeCommit', equals: 0},
            {metric: 'classLoaderCallsAfterCommit', equals: 1},
            {metric: 'classTextCorrect', equals: true},
            {metric: 'done', equals: true},
        ],
    },
];
